const $=id=>document.getElementById(id);
const state={all:[],results:[],selected:new Set(),filter:'all',editing:null,detail:null,candidates:[],request:0};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let toastTimer;
function toast(text){$('toast').textContent=text;$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,6500)}
async function api(path,data){return GoogleStore.api(path,data)}
function attempt(fn){return async event=>{try{await fn(event)}catch(e){toast(e.message)}}}
function openDialog(id){$(id).showModal()}
async function load(){const data=await api('/api/recipes');state.all=data.recipes;const names=new Set(data.ingredients);state.all.forEach(r=>r.ingredients.forEach(i=>i.names.forEach(n=>names.add(n))));$('ingredient-list').innerHTML=[...names].sort((a,b)=>a.localeCompare(b,'pt-BR')).map(n=>`<option value="${esc(n)}">`).join('');$('count-all').textContent=state.all.length;$('count-favorites').textContent=state.all.filter(r=>r.favorite).length;$('count-review').textContent=state.all.filter(r=>!r.reviewed).length;await search();await connectionNote()}
async function search(){const id=++state.request;const result=await api('/api/search',{ingredients:[...state.selected],basics:$('basics').checked,query:$('query').value});if(id!==state.request)return;state.results=result.recipes;render()}
function render(){let list=state.results.filter(r=>state.filter==='favorites'?r.favorite:state.filter==='review'?!r.reviewed:true);if($('complete').checked)list=list.filter(r=>r.complete);$('results-title').textContent=state.selected.size?'Ideias para hoje':state.filter==='favorites'?'Suas favoritas':state.filter==='review'?'Conferir importação':'Seu caderno';$('result-count').textContent=`${list.length} receita${list.length===1?'':'s'}${state.selected.size?' • melhor combinação primeiro':''}`;$('empty').hidden=!!list.length;$('cards').innerHTML=list.map(r=>{const img=RecipeThumbnails.path(r.thumbnail);const mark=/salada|legume|abobrinha|brocolis/i.test(r.title)?'❋':/massa|macarr|arroz|risoto/i.test(r.title)?'≋':'✳';return `<article class="card"><button class="card-main" data-open="${esc(r.id)}"><div class="card-visual">${img?`<img src="${esc(img)}" alt="${esc(r.title)}" loading="lazy" decoding="async" width="640" height="360" data-thumbnail>`:`<span class="food-mark" aria-hidden="true">${mark}</span>`}</div><div class="card-body"><div class="small">${esc(r.tags?.slice(0,2).join(' · ')||'DO SEU CADERNO')}</div><h3>${esc(r.title)}</h3><div class="small">${esc(r.servings||`${r.ingredients.length} ingredientes catalogados`)}</div><div class="card-bottom">${state.selected.size?`${r.score}% dos ingredientes · ${r.missing.length} faltando`:r.warnings?.length?'<span class="badge">Conferir informações</span>':r.reviewed?'✓ Receita conferida':'Importada do seu acervo'}</div></div></button><button class="fav ${r.favorite?'on':''}" data-favorite="${esc(r.id)}" aria-label="${r.favorite?'Remover dos':'Adicionar aos'} favoritos">${r.favorite?'♥':'♡'}</button></article>`}).join('');$('selected').innerHTML=[...state.selected].map(n=>`<button class="chip" data-remove="${esc(n)}">${esc(n)}<span>×</span></button>`).join('')}
async function addIngredient(value){value=value.trim();if(!value)return;const options=[...$('ingredient-list').options];const fold=s=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLocaleLowerCase();const found=options.find(o=>fold(o.value)===fold(value));state.selected.add(found?.value||value);$('ingredient-input').value='';await search()}
function ingredientList(r){const groups=RecipeCore.ingredientGroups(r.ingredients);const headings=groups.some(g=>g.section);return groups.map(g=>`${headings?`<h4 class="ingredient-section">${esc(g.section||'Ingredientes gerais')}</h4>`:''}<ul>${g.items.map(i=>`<li>${esc(RecipeCore.ingredientText(i))}${i.optional?' <small>(opcional)</small>':''}</li>`).join('')}</ul>`).join('')||'<ul><li>Consulte o original abaixo.</li></ul>';}
function detail(r){state.detail=r;$('detail').innerHTML=`<p class="eyebrow">SEU CADERNO DE RECEITAS</p><h2>${esc(r.title)}</h2><p>${esc([r.servings,r.time].filter(Boolean).join(' · '))}</p>${RecipeThumbnails.path(r.thumbnail)?`<img class="detail-img" src="${esc(r.thumbnail)}" alt="${esc(r.title)}" loading="lazy" decoding="async" width="640" height="360" data-thumbnail>`:''}${r.warnings?.length?`<div class="warning">${r.warnings.map(esc).join('<br>')}</div>`:''}${state.selected.size?`<p class="match-list"><strong>Faltam:</strong> ${esc(r.missing?.join(', ')||'Nenhum dos ingredientes catalogados')}${r.warnings?.length?' • A lista pode estar incompleta.':''}</p>`:''}${r.import_notes?.length?`<p class="hint">${r.import_notes.map(esc).join('<br>')}</p>`:''}<div class="detail-columns"><section><h3>Ingredientes</h3>${ingredientList(r)}</section><section><h3>Preparo</h3><ol>${r.steps.map(s=>`<li>${esc(s)}</li>`).join('')||'<li>Consulte o original abaixo.</li>'}</ol></section></div><div class="detail-actions"><button id="edit-current">Editar receita</button><button id="reprocess-current">Reorganizar original</button>${r.source_url&&/^https?:\/\//.test(r.source_url)?`<a href="${esc(r.source_url)}" target="_blank" rel="noopener noreferrer">Ver origem ↗</a>`:''}<button id="delete-current">Excluir</button></div><details><summary>Consultar texto original</summary><pre class="original">${esc(r.original||'Sem texto original.')}</pre>${r.collection_original?`<details><summary>Ver a coletânea completa</summary><pre class="original">${esc(r.collection_original)}</pre></details>`:''}</details>`;$('edit-current').onclick=()=>{$('detail-dialog').close();edit(r)};$('reprocess-current').onclick=attempt(async()=>{$('reprocess-current').disabled=true;try{const next=await api('/api/extract',{text:r.original,title:r.title});$('detail-dialog').close();previewImport(next,r)}finally{$('reprocess-current').disabled=false}});$('delete-current').onclick=attempt(async()=>{if(!confirm(`Excluir “${r.title}”? Ela poderá ser recuperada na planilha.`))return;await GoogleStore.connect();await api('/api/delete',{id:r.id});$('detail-dialog').close();await load();toast('Receita excluída.')} );openDialog('detail-dialog')}
function edit(r){state.editing=structuredClone(r);$('edit-title').value=r.title||'';$('edit-ingredients').value=RecipeCore.formatIngredients(r.ingredients||[]);$('edit-steps').value=(r.steps||[]).join('\n');$('edit-servings').value=r.servings||'';$('edit-time').value=r.time||'';$('edit-url').value=r.source_url||'';$('edit-tags').value=(r.tags||[]).join(', ');$('edit-reviewed').checked=!!r.reviewed;$('edit-warnings').hidden=!r.warnings?.length;$('edit-warnings').textContent=(r.warnings||[]).join(' ');openDialog('edit-dialog')}
function resetPrivateView(){state.all=[];state.results=[];state.editing=null;state.detail=null;state.candidates=[];state.selected.clear();state.request++;document.querySelectorAll('dialog[open]').forEach(d=>d.close());$('cards').replaceChildren();$('detail').replaceChildren();$('ingredient-list').replaceChildren();$('selected').replaceChildren();document.querySelectorAll('textarea,input:not([type=checkbox])').forEach(e=>e.value='');$('edit-form').reset();$('split-list').replaceChildren();$('main').hidden=true;$('login').hidden=false;$('add').hidden=true;}
async function connectionNote(){const s=await api('/api/status');$('sync-note').textContent=(s.persistent?'Cópia salva neste aparelho. ':'Não foi possível guardar a cópia neste aparelho. ')+(s.savedAt?'Última atualização: '+new Date(s.savedAt).toLocaleString('pt-BR')+'. ':'')+(s.authenticated?'Use Atualizar caderno para buscar mudanças do Google.':'Você pode consultar as receitas. O Google será solicitado ao atualizar ou salvar.');}
async function init(){const status=await api('/api/status');const visible=status.authenticated||status.cached;$('main').hidden=!visible;$('login').hidden=visible;$('add').hidden=!visible;if(visible)await load();else resetPrivateView()}
document.addEventListener('error',event=>{const el=event.target;if(!el.matches?.('img[data-thumbnail]'))return;if(el.closest('.card-visual')){const mark=document.createElement('span');mark.className='food-mark';mark.setAttribute('aria-hidden','true');mark.textContent='✳';el.replaceWith(mark);}else el.remove();},true);
window.addEventListener('recipe-connection-changed',()=>{connectionNote().catch(()=>{})});
function previewImport(result,old=null){
 if(result.candidates){state.candidates=result.candidates.map(r=>({...r,thumbnail:old?.thumbnail||r.thumbnail||'',source_url:old?.source_url||r.source_url||''}));$('split-list').innerHTML=state.candidates.map(r=>`<p><strong>${esc(r.title)}</strong><br>${r.ingredients.length} ingredientes · ${r.steps.length} etapas</p>`).join('');$('split-note').textContent=old?'A nota atual será mantida. Você poderá excluí-la depois de conferir as receitas separadas.':'';openDialog('split-dialog');return;}
 edit(old?{...old,...result,id:old.id,thumbnail:old.thumbnail,source_url:old.source_url,favorite:old.favorite,reviewed:false}:result);
}
document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$(b.dataset.close).close());
$('add').onclick=()=>openDialog('add-dialog');$('manual').onclick=()=>{$('add-dialog').close();edit({title:'',ingredients:[],steps:[],warnings:[],thumbnail:'',original:$('source').value})};
$('login-form').onsubmit=attempt(async e=>{e.preventDefault();$('google-login').disabled=true;try{await GoogleStore.connect();await api('/api/refresh');await init()}finally{$('google-login').disabled=false}});
$('logout').onclick=attempt(async()=>{await api('/api/logout',{});resetPrivateView()});
$('refresh').onclick=attempt(async()=>{$('refresh').disabled=true;try{await GoogleStore.connect();await api('/api/refresh');await load();toast('Caderno atualizado.')}finally{$('refresh').disabled=false}});
$('ingredient-input').addEventListener('keydown',attempt(async e=>{if(e.key==='Enter'){e.preventDefault();await addIngredient(e.target.value)}}));$('ingredient-input').addEventListener('change',attempt(async e=>{if([...$('ingredient-list').options].some(o=>o.value===e.target.value))await addIngredient(e.target.value)}));
$('suggestions').innerHTML=['frango','ovo','batata','abobrinha','arroz','salmão'].map(n=>`<button data-ingredient="${n}">＋ ${n}</button>`).join('');$('suggestions').onclick=attempt(async e=>{const b=e.target.closest('[data-ingredient]');if(b)await addIngredient(b.dataset.ingredient)});
$('selected').onclick=attempt(async e=>{const b=e.target.closest('[data-remove]');if(b){state.selected.delete(b.dataset.remove);await search()}});$('clear').onclick=attempt(async()=>{state.selected.clear();await search()});$('basics').onchange=attempt(search);$('complete').onchange=render;let queryTimer;$('query').oninput=()=>{clearTimeout(queryTimer);queryTimer=setTimeout(attempt(search),200)};
$('filters').onclick=e=>{const b=e.target.closest('[data-filter]');if(!b)return;state.filter=b.dataset.filter;document.querySelectorAll('#filters button').forEach(x=>x.classList.toggle('active',x===b));render()};
$('cards').onclick=attempt(async e=>{const fav=e.target.closest('[data-favorite]');if(fav){await GoogleStore.connect();const r=state.all.find(x=>x.id===fav.dataset.favorite);await api('/api/save',{...r,favorite:!r.favorite});await load();return}const b=e.target.closest('[data-open]');if(b)detail(state.results.find(r=>r.id===b.dataset.open))});
$('extract-form').onsubmit=attempt(async e=>{e.preventDefault();const value=$('source').value.trim();const button=$('extract-button');button.disabled=true;button.textContent='Organizando…';try{const r=await api('/api/extract',/^https?:\/\/\S+$/.test(value)?{url:value}:{text:value});$('add-dialog').close();previewImport(r)}finally{button.disabled=false;button.textContent='Organizar receita →'}});
$('edit-form').onsubmit=attempt(async e=>{e.preventDefault();$('save-button').disabled=true;try{await GoogleStore.connect();const old=state.editing;const text=$('edit-ingredients').value;const ingredients=text===RecipeCore.formatIngredients(old.ingredients||[])?old.ingredients:(await api('/api/normalize',{text})).ingredients;await api('/api/save',{...old,title:$('edit-title').value,ingredients,steps:$('edit-steps').value.split('\n').filter(x=>x.trim()),servings:$('edit-servings').value,time:$('edit-time').value,source_url:$('edit-url').value,thumbnail:$('edit-url').value===old.source_url?old.thumbnail:'',tags:$('edit-tags').value.split(',').map(x=>x.trim()).filter(Boolean),reviewed:$('edit-reviewed').checked});$('edit-dialog').close();await load();toast('Receita guardada.')}finally{$('save-button').disabled=false}});
$('save-split').onclick=attempt(async()=>{$('save-split').disabled=true;try{const result=await api('/api/save-batch',{recipes:state.candidates});$('split-dialog').close();await load();toast(`${result.added} receitas separadas para conferência.`)}finally{$('save-split').disabled=false}});
init().catch(e=>toast(e.message));


if(window.RECIPE_CONFIG?.spreadsheetId)$('sheet-link').href='https://docs.google.com/spreadsheets/d/'+encodeURIComponent(window.RECIPE_CONFIG.spreadsheetId)+'/edit';
